### ISSUE TITLE
Spinner flashes initial values before showing the new values

### ISSUE THREAD

**Issue by Aquive** [trinos-nl/magento2-postcode-nl#15]
Steps to reproduce:

- Add product to cart and go to checkout
- Fill in complete address form
- Change the postcode and housenumber field fast (eg. from `1000 AK `  and  `25`  to  lets say `9700 ZZ` and, `80`. 
- The spinner in the housenumber field is shown. and the initial housenumber `25` is shown (after it is changed to `80`) after the request is done the right new housenumber is shown, in my example `80`.

While testing this for my bug report more quirky stuff seems to happen. When filling in a number which doesnt exists it just resets to the old value? I think it all comes down to filling in the form and it needs to do a request and resets to a state when the requests was done, or something? I didn't look into the code yet.

**Comment by thijsdewitt** [comment]
Hi @Aquive This is a known issue in the Hyva checkout and should be fixed when the new the shipping and billing forms are using the new form abstraction. This issue is not related to this module.
