### ISSUE TITLE
Postcode + number combination not working correctly

### ISSUE THREAD

**Issue by JHFruitcake** [trinos-nl/magento2-postcode-nl#19]
When there's an addition for a postcode+number combination (like 33a), a second field should appear after 'number' where this can be entered. This functionality is not working correctly. 
For now, users can choose 'Manually fill in address' and still enter whatever they want.

**Comment by thijsdewitt** [comment]
If you set `customer/address/street_lines` to 3. You should see the third street field used for the addition field. I should clarify this in the README

**Comment by JHFruitcake** [comment]
Yes this solved the issue, thanks
