### ISSUE TITLE
Housenumber addition gets cleared after selecting an option

### ISSUE THREAD

**Issue by Tjitse-E** [trinos-nl/magento2-postcode-nl#4]
### Steps to reproduce
1. Enter a postcode and housenumber combination that have additions
2. Select one of the additions from the select

### Expected result
The addition gets saved correctly with the address

### Actual result
The addition gets cleared after selecting a value.

**Comment by thijsdewitt** [comment]
Thanks for the contribution! Your Pull request has been merged.
